r = input('Digite algo: ')
print(f'O tipo primitivo desse valor e {type(r)}')
print(f'Só tem espaços?{r.isspace()}')
print(f'É númerico?{r.isnumeric()}')
print(f'É alfabético?{r.isalpha()}')
print(f'É alfanumérico?{r.isalnum()}')
print(f'Esta em maiúsculo?{r.isupper()}')
print(f'Esta em minúsculo?{r.islower()}')
print(f'Esta capitalizada?{r.istitle()}')
